### ISSUE TITLE
Potential support for python 2

### ISSUE THREAD

**Issue by patrick-motard** [SuperCuber/dotter#1]
Hey, 
I saw your post about this tool on /r/unixporn and wanted to try it out. Looks like it could potentially be what I need. Wanted to get some thoughts from you. OSX comes with python 2.7 out of the box. Running ./dotter -h as the README suggests doesn't work of course if python3 isn't installed. I've done very little with python and would like some advice. What level of effort would be involved in refactoring this project to support both versions of python? Is it something you'd be willing to merge into your code?

**Comment by SuperCuber** [comment]
I don't really plan on supporting python 2, but if you want to fix it I have no problem merging it in.
