### ISSUE TITLE
Readme and Wiki aren't good enough

### ISSUE THREAD

**Issue by SuperCuber** [SuperCuber/dotter#10]
Ideas:
- [x] Split README off into Wiki
- [x] Explain the advantages over GNU Stow
   - [x] Opt-in templating - advantage and disadvantage
   - [x] Override target location
- [ ] Compare with chezmoi using [this](https://github.com/twpayne/chezmoi/blob/master/docs/HOWTO.md#use-templates-to-manage-files-that-vary-from-machine-to-machine) and [this](https://github.com/twpayne/chezmoi#i-already-have-a-system-to-manage-my-dotfiles-why-should-i-use-chezmoi)
---
- [x] Get feedback on completeness of wiki so far
- [x] Add more entries to FAQ

**Comment by SuperCuber** [comment]
- [ ] Get feedback on completeness of wiki so far
- [ ] Add more entries to FAQ

**Comment by mfiano** [comment]
The documentation is actually pretty good considering the small API. I think this was well written for sure.

**Comment by mfiano** [comment]
The only thing I found a little unintuitive was the fact that package variables aren't namespaced, or rather, they can be accessed by their fully-qualified package+name, but I would have liked the same variable in 2 different packages to be unique variables. I can live without that though.

**Comment by SuperCuber** [comment]
> The only thing I found a little unintuitive was the fact that package variables aren't namespaced, or rather, they can be accessed by their fully-qualified package.name, but I would have liked the same variable in 2 different packages to be unique variables. I can live without that though.

You can emulate that with `[package_name.variables.package_name]` once your issue is fixed or with more specific naming.\
The reason the packages are all merged together is because I wanted to access variables between them, and also have "variable-only" packages.
