### ISSUE TITLE
Condition on the destination path depending on the OS?

### ISSUE THREAD

**Issue by sneko** [SuperCuber/dotter#100]
Hi,

The Visual Studio Code `settings.json` is set in total different locations depending on the OS as mentioned in https://stackoverflow.com/questions/44575312/change-vscode-user-settings-location

I saw @SuperCuber you mentioned some conditioning possible but how to do it to check the OS platform, and adjust the destination path?

Any example would be appreciated :) 

Thank you,

**Comment by SuperCuber** [comment]
Take my dotfiles as an example - my [global.toml](https://github.com/SuperCuber/dotfiles/blob/6b6f43e1e550987097d0f51fc9d06a03d2679ba5/.dotter/global.toml#L80) and this is the file I include on my windows machine [windows.toml](https://github.com/SuperCuber/dotfiles/blob/6b6f43e1e550987097d0f51fc9d06a03d2679ba5/.dotter/include/windows.toml#L2)

There's no automatic conditioning, I just add `includes = [".dotter/include/windows.toml"]` in my local.toml

**Comment by sneko** [comment]
Since `local.toml` is .gitignored I guess you mean that people cloning my dotfiles repo should modify it to include their own OS file?

That's sad there is no way to automate this hmmmm

**Comment by SuperCuber** [comment]
Feel free to reopen if you still have questions
