### ISSUE TITLE
[BUG] Using recurse=false on window creates a file symlink instead of dir.

### ISSUE THREAD

**Issue by LucasOe** [SuperCuber/dotter#101]
## Environment
- **OS**: Windows 10 21H2
- **Dotter version**: 0.12.11

## Description
When using the option `recurse=false` on a symbolic link, dotter creates a file symlink instead of linking the directory.

## Reproduction
Create any symbolic link with `recurse=false`. Example:
```
[test.files]
"mydir" = { target = "~/mydir", type="symbolic", recurse=false }
```

### Expected behavior
Because using `recurse=false` would only make sense when linking directories, I would expect ~/mydir to be a directory.

### Actual behavior
The created symlink is a [file symlink](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_file.html) instead of a [dir symlink](https://doc.rust-lang.org/std/os/windows/fs/fn.symlink_dir.html), making it impossible to see the content of the linked directory. The created symlink should have the mode `l-r--` but it's mode is `la---` instead, when inspecting it with ls. Changing the Rust function linked above when not linking recursively should be enough to fix this issue.

**Comment by SuperCuber** [comment]
I cannot reproduce this - current code for me creates a symlink with mode `lrwxrwxrwx` when running `ls -Ahl` on git-bash, and commands like `cd mydir` and `ls mydir` work as I'd expect.

I could implement a fix that checks if the source file is a dir and uses the appropriate function but I wouldn't be able to verify that it works.

**Comment by SuperCuber** [comment]
funnily enough I'm getting this:
![](https://owo.whats-th.is/bJmgRCj.png)

the solution is `rm mydir` without the slash

**Comment by LucasOe** [comment]
I can cd into it when using the Git Bash, but not using PowerShell 7.2.5. You also can't navigate the file in the Explorer.

**Comment by SuperCuber** [comment]
>You also can't navigate the file in the Explorer.

This I can reproduce, pushing a fix soon :)

**Comment by LucasOe** [comment]
That was fast, thanks for the fix :)
