### ISSUE TITLE
[FEATURE] Builtin variable containing the path of the dotter root directory

### ISSUE THREAD

**Issue by mattiasflodin** [SuperCuber/dotter#106]
Sometimes I need helper scripts to do additional stuff, for example I have an initialization bash script that is executed from my i3 config. It seems unnecessary to install those anywhere when I can just reference them directly in my dotter root directory. But that requires me to know where that directory is. Right now I have a variable for that and set it in local.toml for every machine, but this is knowledge that dotter already has when running so it would be nice to have it available as a builtin instead.

**Comment by SuperCuber** [comment]
See https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#builtin-variables - `dotter.current_dir` should be what you're looking for.
