### ISSUE TITLE
Unconventional Flag for Version

### ISSUE THREAD

**Issue by SunnySoldier357** [SuperCuber/dotter#12]
In most CLI programs `-v` or `--version` prints out the version info. `dotter` uses `-V` instead of `-v` which is a weird choice.

**Comment by SuperCuber** [comment]
I'm not sure that's the case. Usually `-v` stands for `--verbose`, and `-V` stands for `--version`. Some examples I could find:
* `man`
* `ls` - doesn't use `-V` but not `-v` either
* `clear`

There's programs that use `-v` as well, like `apt`.

Basically what I'm saying is that there's some that do this and some that do that.
Regardless it's a default from the `structopt/clap` library: as you can see in [this file](https://github.com/SuperCuber/dotter/blob/5675f16266c9e03eea28d5fd94ff6e8f6cb3478d/src/args.rs) I don't even configure a version flag.
