### ISSUE TITLE
Failed to deploy, invalid type

### ISSUE THREAD

**Issue by mnivoliez** [SuperCuber/dotter#13]
Hello, I have try to use dotter but while executing the command, I end up with this:

```bash
dotter --dry-run
[INFO ] Changing directory to "."
[INFO ] Loading configuration...
Error: Failed to deploy

Caused by:
    0: Failed to get a configuration.
    1: Failed to parse config file dotter_settings/global.toml
    2: Failed to parse file dotter_settings/global.toml
    3: invalid type: string "i3", expected a map
```

Here are my dotter settings:
global.toml:
```toml
[i3.files]
"i3" = "~/.config/i3"
"i3blocks" = "~/.config/i3blocks"
```
local.toml:
```toml
packages = ["i3"]
```

**Comment by mnivoliez** [comment]
Issue resolve, it was just a cache issue

**Comment by SuperCuber** [comment]
Hey, given your posted configuration there shouldn't have been an issue. I'm curious what you mean by "cache issue"? Do you mean the Dotter cache folder?

**Comment by mnivoliez** [comment]
Hello, well basically the issue was of vim cache. It displayed the content of global.toml as the content of local.toml and vice versa. One reboot later and the cache reset.

**Comment by SuperCuber** [comment]
I see. Feel free to open more issues if you encounter more problems :D
