### ISSUE TITLE
Missing release on GitHub?

### ISSUE THREAD

**Issue by orhun** [SuperCuber/dotter#133]
### The question

Hey,

A user on the AUR reported that `dotter` is updated to `0.13.0` on [crates.io](https://crates.io/crates/dotter/0.13.0) but not on GitHub.

Is it possible to get this release published on GitHub as well?

Thank you!
🐻

**Comment by SuperCuber** [comment]
🤦 i updated version in cargo.toml to 0.13 but in github called it 0.12.16
Guess I'll add another 0.13 release at the same commit

**Comment by SuperCuber** [comment]
BTW hopefully the `completions.zip` is more convenient for packaging vs the previous way, let me know if any improvements can be made to it. (this is an additional thing, not removing existing completions)

**Comment by orhun** [comment]
> i updated version in cargo.toml to 0.13 but in github called it 0.12.16

Oh, I see 😅 

> BTW hopefully the completions.zip is more convenient for packaging vs the previous way

Definitely, just incorporated them in the [`dotter-rs-bin`](https://aur.archlinux.org/packages/dotter-rs-bin) package.

All good now, thanks!
