### ISSUE TITLE
[FEATURE] Pass variables/parameters to include_template helper

### ISSUE THREAD

**Issue by iliekturtles** [SuperCuber/dotter#134]
I am attempting to have my pre/post deploy/undeploy scripts conditionally `include_template` the associated script for enabled packages instead of writing everything in the top-level scripts and using `{{#if dotter.packages...}}` checks. I currently have the following code duplicated in all four combinations with the only change being the file name in the `assign` helper.

```handlebars
{{! Package scripts, $package/$stage_deploy.sh }}
{{#each dotter.packages}}
{{assign "deploy" (concat @key "/post_undeploy.sh")}}
{{#if (and this (command_success (concat "test -f " ../deploy)))}}
{{include_template ../deploy}}
{{/if}}
{{/each}}
```

Instead of duplicating this code in every file it would be great to be able to pass variables/parameters into the template.

**Describe the solution you'd like**
One of the two options would resolve the issue:

 1. Allow `include_template` to accept parameters:
```handlebars
{{include_template "file" { parameter1: "value1", ... } }}
```

 2. Use the same context created by the `assign` helper in the template:
```handlebars
{{assign "parameter1" "value1"}}
{{include_template "file"}}
```

**Describe alternatives you've considered**
It's possible this may be an upstream bug in [handlebars_misc_helpers](https://github.com/davidB/handlebars_misc_helpers). The helper clones the `ctx` parameter, assigns the value, and sets the result to the render context. Calling `assign` multiple times in a row leaves the render context only containing the last assignment call. `include_template` is called using the context rather than the render context, meaning that any assigned value is not available.

https://github.com/davidB/handlebars_misc_helpers/blob/0e60d86cc5ed905bb65987734bb72f360861365a/src/assign_helpers.rs#L38-L43

**Comment by SuperCuber** [comment]
Both `assign` and `include_template` are in other crates, please open issues/PRs in those. Let me know when they are fixed and I'll update the libs :)

**Comment by iliekturtles** [comment]
Thanks for the feedback. I finally had time to review and opened davidB/handlebars_misc_helpers#65.

For `include_template`, the relevant code seems to be in this crate.

https://github.com/SuperCuber/dotter/blob/eb51da9bde241e77c05ffb8f2b632678c448ea9b/src/handlebars_helpers.rs#L102-L108

The actual `render_template_with_context` implementation is in the `handlebars` crate but it is being called with the `ctx` context parameter which could possibly be modified or replaced with `render_context.context()`. I'll wait for feedback on the `handlebars_misc_helpers` issue I opened for the time being.

https://github.com/SuperCuber/dotter/blob/eb51da9bde241e77c05ffb8f2b632678c448ea9b/src/handlebars_helpers.rs#L122-L124

**Comment by SuperCuber** [comment]
You're right. Are you able to test out that change in a PR? Should be simple enough to fix

**Comment by iliekturtles** [comment]
The change below passes an initial round of local testing. I didn't get a chance to package it up into a full PR, and do think it would be good to get feedback in https://github.com/davidB/handlebars_misc_helpers/issues/65.

```diff
diff --git a/src/handlebars_helpers.rs b/src/handlebars_helpers.rs
index 88c76a6..8ea5bc3 100644
--- a/src/handlebars_helpers.rs
+++ b/src/handlebars_helpers.rs
@@ -103,7 +103,7 @@ fn include_template_helper(
     h: &Helper<'_, '_>,
     handlebars: &Handlebars<'_>,
     ctx: &Context,
-    _: &mut RenderContext<'_, '_>,
+    rc: &mut RenderContext<'_, '_>,
     out: &mut dyn Output,
 ) -> HelperResult {
     let mut params = h.params().iter();
@@ -120,7 +120,7 @@ fn include_template_helper(
     let included_file = std::fs::read_to_string(path)
         .map_err(|e| RenderError::from_error("include_template", e))?;
     let rendered_file = handlebars
-        .render_template_with_context(&included_file, ctx)
+        .render_template_with_context(&included_file, rc.context().as_deref().unwrap_or(ctx))
         .map_err(|e| RenderError::from_error("include_template", e))?;
 
     out.write(&rendered_file)?;
```
