### ISSUE TITLE
"data did not match any variant of untagged enum FileTargetOuterRepr"

### ISSUE THREAD

**Issue by Cornelius-Figgle** [SuperCuber/dotter#137]
### Environment
If applicable, provide the following details:
- **OS**: All (Windows 10 / Debian 12 / Arch Linux)
- **Dotter version**: 0.13.0

### The question
When running `dotter deploy`, the following error is thrown:

```shell
[ERROR] Failed to deploy
Caused by:
    get a configuration
    load global config ".dotter/global.toml"
    deserialize file contents
    data did not match any variant of untagged enum FileTargetOuterRepr
```

I would assume this to be a problem with the format of my config files but I can't see anything. What am I missing here?

### Files

[`global.toml`](https://github.com/Cornelius-Figgle/dotfiles/blob/82b48cec57a901d38523b849064fdabd706f1106/.dotter/global.toml)
[`local.toml` (on Debian)](https://github.com/Cornelius-Figgle/dotfiles/blob/82b48cec57a901d38523b849064fdabd706f1106/.dotter/mimic4.toml)

**Comment by SuperCuber** [comment]
I looked at adding a more specific error message but I'm just passing the whole file to the deserialization library, so my code doesn't know what specific entry is the problem :(

I can't spot anything at a glance either, you could try commenting out everything then uncommenting each package on its own to track down the issue.

**Comment by Cornelius-Figgle** [comment]
> you could try commenting out everything then uncommenting each package on its own to track down the issue

Hmm okay, I will try this and see what comes up

**Comment by Cornelius-Figgle** [comment]
![image](https://github.com/SuperCuber/dotter/assets/110970234/7a983a56-7cf8-400e-9153-735f0e7a0dfa)

I used a [toml syntax validator](https://toml-lint.com/) to find the exact error, I had used the same filename twice 😕

**Comment by SuperCuber** [comment]
interesting, i wonder if it set the value to an array of the two strings then? 🤷

**Comment by Cornelius-Figgle** [comment]
Just fixed the duplicate filename and it still throws the same error even thought the validator says it is now correct?

**Comment by SuperCuber** [comment]
yeah thats not too strange since it wasn't a syntax error, its an error that some value is not the expected type.
try the commenting strategy 🤷

**Comment by Cornelius-Figgle** [comment]
Okay will go do that. Out of interest, what it 'deserialisation' and what is it used for within `dotter`?

**Comment by Cornelius-Figgle** [comment]
I have narrowed it down to the following line:

```toml
"config/helix/themes" = {target="~/.config/helix/themes", type="symbolic", recursive=false}
```

Can you spot the problem here? I would like it to link the whole directory across, ie the same as `ln -sd abc xyz`

**Comment by SuperCuber** [comment]
Deserialization = transforming stored data in some format (like toml) into in-memory data that the program can use (structs/classes/whatever)

For your config, the option is named `recurse`, not `recursive`

I tried looking for it in the wiki but I don't think it's mentioned anywhere, gotta add it sometime

**Comment by Cornelius-Figgle** [comment]
Ah that works! Thanks :)
