### ISSUE TITLE
[BUG] Tests fail because file doesn't exist

### ISSUE THREAD

**Issue by Cornelius-Figgle** [SuperCuber/dotter#144]
## Environment
- **OS**: Void Linux (xbps-src)
- **Dotter version**: v0.13.0
- Attempting to use `xbps-src` to build `dotter` on Void Linux

## Description
`src/handlebars_helpers.rs:401` is trying to test that the templating engine will say this file isn't executable, but it's dying because the file doesn't exist

## Reproduction

[template](https://pastebin.com/kGCmPNRz)

```bash
./xbps-src -Q pkg dotter
```

### Expected behavior
It should be creating the file instead

### Actual behavior
[output from `export RUST_BACKTRACE=full`](https://pastebin.com/KW5bmDhJ)

**Comment by SuperCuber** [comment]
This is because on unix dotter uses `which` 's exit code to check whether a command is executable. I guess in your environment `which` doesn't exist. Is there a different way that doesn't depend on it?

**Comment by Cornelius-Figgle** [comment]
> I guess in your environment which doesn't exist.

That appeared to be the issue, adding `which` to the `checkdepends` seemed to fix the issue
