### ISSUE TITLE
Unecessary 

### ISSUE THREAD

**Issue by JaydenElliott** [SuperCuber/dotter#147]
Hey, i'm using dotter across multiple machines/os/distros so like the idea of global + individual toml files, however I am having trouble understanding the use of `local.toml`. What would the difference be between the following two setups?

1. having a `local.toml` + `ubuntu.toml` that defines all the unique symlinks

`local.toml`
```
includes = [".dotter/ubuntu.toml"]
```

2. having no `local.toml` and running `dotter deploy -l ubuntu.toml`

In case 2, i would check in my `global.toml` + `ubuntu.toml` to git, and not have to worry about creating a `local.toml` on a new machine, unless necessary, upon which only then would i create a local.toml and include it in the ubuntu.toml file. 

Cheers, love the package :)

**Comment by SuperCuber** [comment]
This is one of the possible use cases. To make this easier, the option to use hostname-based local.toml was added a while ago. I didn't add it to wiki until now, check out the freshly written section [here](https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#hostname-local-toml)

**Comment by JaydenElliott** [comment]
awesome thanks, ill use that!
