### ISSUE TITLE
How does dotter know where the dotfiles are at?

### ISSUE THREAD

**Issue by RobioEpo** [SuperCuber/dotter#166]
### Environment
If applicable, provide the following details:
- **OS**: Linux distribution
   - Arch
- **Dotter version**: Find out using `dotter -V`
   - 0.13
- **Additional relevant information**

### The question
Ask your question here.
how does dotter know where the dotfiles are at?

I keep getting this error.

`dotter -d --verbose 
[ERROR] Failed to deploy
Caused by:
   get a configuration
   load global config ".dotter/global.toml"
   file not found
`

**Comment by SuperCuber** [comment]
Check out the setup guid

https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration
