### ISSUE TITLE
[FEATURE] Add a command to checkout remote repo

### ISSUE THREAD

**Issue by VPraharsha03** [SuperCuber/dotter#168]
**Is your feature request related to a problem? Please describe.**
Currently the only pre-requisite for dotter to run on a new machine is git, particularly on windows git doesn't come pre-installed, if dotter could implement a command (say `fetch`) to checkout dotfiles repo on a new windows machine that would simplify the process by just only requiring to install dotter binaries. This might help simplify deployment process by reducing commands to a single command.

**Describe the solution you'd like**
probably something like `dotter --fetch https://github.com/username/dotfiles.git`, this is similar to what `chezmoi` implements

**Describe alternatives you've considered**
using git to clone dotfiles or downloading the source code archive (curl) and extracting it using `Expand-Archive` or `tar` commands (on Windows 10).

**Comment by SuperCuber** [comment]
After you clone the repo you will probably want to pull or add/commit stuff anyways... I don't think the convenience of quickly setting up a machine without git is a good enough reason to implement a whole git client.
