### ISSUE TITLE
[BUG] v0.13.1 reports wrong version

### ISSUE THREAD

**Issue by vserrago** [SuperCuber/dotter#170]
## Environment
- **OS**: Arch Linux
- **Dotter version**: 0.13.1
- **Additional relevant information**: Installed via the [dotter-rs-bin aur package](https://aur.archlinux.org/packages/dotter-rs-bin)

## Description
The latest release (v0.13.1) reports the wrong version string. Looking at the v0.13.1 version of [Cargo.toml](https://github.com/SuperCuber/dotter/blob/v0.13.1/Cargo.toml), it looks like the version was not incremented.

However, I'm not sure that there's much to be done here, as it has already been incremented for the [next release](https://github.com/SuperCuber/dotter/blob/d38a5ddc243b38b4ab6da8759b0cecdb9f26945e/Cargo.toml#L3) . I wasn't sure this was worth reporting, but it threw me for a loop trying to figure out why I wasn't running the latest version despite being up-to-date, so maybe it might help someone who might have the same question.

## Reproduction
Execute `dotter --version` on ` dotter-linux-x64-musl` from [the latest release](https://github.com/SuperCuber/dotter/releases/tag/v0.13.1).

### Expected behavior
```
$ dotter --version
dotter 0.13.1
```

### Actual behavior
```
$ dotter --version
dotter 0.13.0
```

**Comment by SuperCuber** [comment]
Yep, it will be included in next release 🫠
