### ISSUE TITLE
[FEATURE] Add convenience features

### ISSUE THREAD

**Issue by SuperCuber** [SuperCuber/dotter#19]
Currently editing files and configurations is a bit tedious/annoying, I want to make it as comfortable as possible.

### Command-line flags (and variables in general)
I want to be able to add a variable on the command line for testing purposes that will overwrite whatever it would be set to otherwise.

For example I want to see how the config will look with a flag toggled to true, I want to run `dotter flag=true` and observe the result

Idea: I can read toml from stdin when I have a certain flag, then merge it as another "local.toml"-type step

- [x] Implement
- [x] Document

### Diffing
In relation to command-line flags, I want to see the difference they make without having to open the target file and having to remember what it was previously.

- [x] Implement
- [x] Implement watch+diff
- [x] Document

**Comment by SuperCuber** [comment]
## Running watch-style

Seems like the package watchexec can help - [this file](https://github.com/watchexec/watchexec/blob/main/src/run.rs) seems like a good entry point.

**They say you need to pin version because they don't follow semver**

**Comment by mfiano** [comment]
Diffing, 100% this.

**Comment by SuperCuber** [comment]
Note about diffing - now `-v` flag is used
