### ISSUE TITLE
Need a better explanation

### ISSUE THREAD

**Issue by thorntonjohn** [SuperCuber/dotter#2]
I read your readme and I have no idea what this actually does. I think if you explained it better you may have more interest.

**Comment by SuperCuber** [comment]
You can check out the example, I will probably add a text one in the readme later

**Comment by SuperCuber** [comment]
At long last, I wrote a pretty decent explanation.
I still have the section describing **caching** left to document - I will complete it after #6 is done.

**Comment by SuperCuber** [comment]
After 3.5 years, this is done.
