### ISSUE TITLE
[FEATURE] Explicitly indicate if the file is a template or not

### ISSUE THREAD

**Issue by mnivoliez** [SuperCuber/dotter#20]
**Is your feature request related to a problem? Please describe.**
Some file are recognized as template when they are not. For exemple some vim script.

**Describe the solution you'd like**
A way to indicate that the file is not a template (in global.toml or at the start of the file) or a way to toggle off the feature alltogether.

**Describe alternatives you've considered**
Remove "{{" and "}}" in files but not always possible

**Comment by SuperCuber** [comment]
This is a problem I've thought of but put off, specifying in global seems like a good idea.

I've been also thinking in #18 about extending the configuration to allow dictionaries as values of files, so this could be one of the features that extension allows.

**Comment by mnivoliez** [comment]
Another thing to consider is if the file should be detected as a template unless being told otherwise, or if the inverse behaviour is prefered (it's not a template until the user declare the file as a template). we can even imagine that there could be a toggle to change this behaviour.

**Comment by SuperCuber** [comment]
And a reminder for myself:
- [ ] Update documentation when this is implemented

**Comment by SuperCuber** [comment]
@mnivoliez I merged this into #18, I would like your opinion on other keys that could be useful.

**Comment by SuperCuber** [comment]
> if the file should be detected as a template unless being told otherwise, or if the inverse behaviour is prefered

I think I will keep the current behavior since it will make it work in most cases, and the cases that don't work you can override it.
