### ISSUE TITLE
[BUG] Cargo.lock needs to be added

### ISSUE THREAD

**Issue by orhun** [SuperCuber/dotter#27]
## Environment
- **OS**: Arch Linux
- **Dotter version**:  -
- **Additional relevant information**
https://doc.rust-lang.org/cargo/faq.html#why-do-binaries-have-cargolock-in-version-control-but-not-libraries

## Description
Using `--locked` flag with `cargo build` fails because `Cargo.lock` is not present in the project.
Usage of `--locked` flag is important for the [AUR package](https://aur.archlinux.org/packages/dotter-rs)'s [reproducibility](https://wiki.archlinux.org/index.php/Reproducible_Builds).

(I also recommend you to release a new version after adding the `Cargo.lock` file)

## Reproduction
1. Checkout the repository.
2. Run any cargo command with `--locked` flag. (e.g. `cargo build --locked`)

### Expected behavior
Successful build.

### Actual behavior
```bash
$ cargo build --release --locked
error: Cargo.lock needs to be updated but --locked was passed to prevent this
If you want to try to generate the lock file without accessing the network, use the --offline flag.
```

**Comment by SuperCuber** [comment]
Firstly, thanks for going through the trouble of packaging this for the AUR! I don't use Arch myself but I have used it in the past, so it's very cool to see my project entering the ecosystem.

I've added it in 045ec2bc6c6f246ef5918ee35d4bb62b5f3a426c as you recommended.

---

I would like to ask - will new commits on master automatically go into the package? Or is it manual?

Actually, I see that there is `dotter-rs`, `dotter-rs-git`, and `dotter-rs-bin`.
I assume you update `dotter-rs` and `dotter-rs-bin` manually while `dotter-rs-git` follows master - I think I've seen this pattern before. I have described them in 14ba161fa2080223ba3d2d2509f461d8e12d77f9 .

**Comment by orhun** [comment]
> I've added it in [045ec2b](https://github.com/SuperCuber/dotter/commit/045ec2bc6c6f246ef5918ee35d4bb62b5f3a426c) as you recommended.

Thanks 👍🏼 

> I would like to ask - will new commits on master automatically go into the package? Or is it manual?

`-git` package pulls the latest state of the repository and builds the package from there. About the other packages, I get notified (through email and [nvchecker](https://github.com/lilydjwg/nvchecker/)) when you create a new release and I manually update them.

> Actually, I see that there is `dotter-rs`, `dotter-rs-git`, and `dotter-rs-bin`.
> I assume you update `dotter-rs` and `dotter-rs-bin` manually while `dotter-rs-git` follows master - I think I've seen this pattern before. I have described them in [14ba161](https://github.com/SuperCuber/dotter/commit/14ba161fa2080223ba3d2d2509f461d8e12d77f9) .

Exactly!

**Comment by SuperCuber** [comment]
@orhun Give me a couple minutes to sort out the github action that builds it - I will re-create the 0.9.1 tag in a sec

**Comment by SuperCuber** [comment]
@orhun action's running - feel free to close this issue if that's all.

Thanks again for volunteering to do this, greatly appreciated and kinda made my day :)
