### ISSUE TITLE
create files on dotter deploy?

### ISSUE THREAD

**Issue by salkin-mada** [SuperCuber/dotter#38]
### Environment
- **OS**: Arch Linux 5.9.1-rt20-1-rt
- **Dotter version**: 0.10.7
- **I am migrating from `dotbot`**

### The question
This is maybe a feature request, but not sure - maybe `dotter` already does the following.
Is it possible to do something like `[create]`. A global addition to `files` and `variables` in packages maybe?
I am migrating from `dotbot` and I dont know how to do the following here in `dotter`.
```yaml
- create:
    - ~/.vim_undofiles
```
this is a file which is created first time my dotfiles are deployed/installed and only if the file does not already exist.
`.vim_undofiles` is where i keep my persistent undo history for `nvim` which my `init.lua` references. So it needs to be created by my dotfiles system on init system setups. I guess behind the scene its just a simple `mkdir -p $1`

can `dotter` do this or change issue type to FR?

Thanks for a nice rust dotfile sys. Fantastic work!

**Comment by SuperCuber** [comment]
This is not possible right now.

I assume you mean you want this to be an empty directory and not a file, right?

For now you could handle it similarly to how you do it in git, with a conventional `.gitkeep` file in the directory and then deploying the directory which will actually just deploy the file and create the directory along the way

**Comment by salkin-mada** [comment]
I was a bit vague. I actually want to deploy both empty files and empty directories.
good point about the `.gitkeep` or `.something_something` file. Maybe just deploy it first time and add it to the `.gitignore`.
But I can just script the creation of empty folders and files needed for my `nvim` sessions and persistent undo history in `lua` on vim init. Actually this makes more sense than giving the dotfile repo "handler" the responsibility. I was just doing this earlier with `dotbot` because the `[create]` possibilities with the `install.conf.yaml`
Not really sure if this is something which is needed of a dotfile repo deployer / handler / installer.
What do you think? Is this something `dotter` should be able to do?

**Comment by SuperCuber** [comment]
Yeah I agree, empty files and dirs are not generally useful enough to have dedicated configuration sections just for that.
