### ISSUE TITLE
Not able to deploy dotfile containing vim foldmarkers

### ISSUE THREAD

**Issue by salkin-mada** [SuperCuber/dotter#39]
## Environment
- **OS**: Arch Linux 5.9.1-rt20-1-rt
- **Dotter version**: 0.10.7

## Description
`dotter` mistakes my `kitty` config file for being a handlebars template.
the `kitty.conf` file contains a lot of `{{{`

## Reproduction
example **snippet** from a kitty conf containing vim fold markers
```
# vim:fileencoding=utf-8:ft=conf:foldmethod=marker

#: Fonts {{{

font_family      Fira Code
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14.0
force_ltr no
```

### Expected behavior
Successful deployment of my config file for `kitty`. And some .mustache theme templates.

### Actual behavior
`dotter` mistakes the `kitty` config file for being a handlebars template and fails.
And `dotter` mistakes the template folder in my kitty theme folder e.g. `kitty/themes/templates/default-256.mustache` with something it should do something with. I guess also handlebars templating.

```
.filer on  system-audio [✘!?]
V ./dotter
[ERROR] Failed to create template template "kitty/kitty.conf" -> "/home/rand/.config/kitty/kitty.conf"
Caused by:
    perform template deployment
    render template
    Template error: invalid handlebars syntax.
    --> Template error in "Unnamed template":5:1
     |
   2 | #: Fonts {{{
   3 |
   4 | #: kitty has very powerful font management. You can configure
     |-^-----------------------------------------------------------
   5 | #: individual font faces and even specify special fonts for particular
   6 | #: characters.
   7 |
   8 | font_family			Fira Code
     |
     = reason: invalid handlebars syntax.

    Template error: invalid handlebars syntax.
    --> Template error in "Unnamed template":5:1
     |
   2 | #: Fonts {{{
   3 |
   4 | #: kitty has very powerful font management. You can configure
     |-^-----------------------------------------------------------
   5 | #: individual font faces and even specify special fonts for particular
   6 | #: characters.
   7 |
   8 | font_family			Fira Code
     |
     = reason: invalid handlebars syntax.

[ERROR] Failed to create template template "kitty/themes/templates/default-256.mustache" -> "/home/rand/.config/kitty/themes/templates/default-256.mustache"
Caused by:
    perform template deployment
    render template
    Error rendering "Unnamed template" line 1, col 10: Variable "scheme-name" not found in strict mode.
    Error rendering "Unnamed template" line 1, col 10: Variable "scheme-name" not found in strict mode.
[ERROR] Failed to create template template "kitty/themes/templates/default.mustache" -> "/home/rand/.config/kitty/themes/templates/default.mustache"
Caused by:
    perform template deployment
    render template

```
and additions on the tail with RUST_LOG=trace
```
    Error rendering "Unnamed template" line 1, col 10: Variable "scheme-name" not found in strict mode.
    Error rendering "Unnamed template" line 1, col 10: Variable "scheme-name" not found in strict mode.
```

**Comment by salkin-mada** [comment]
same folder name problem with my `pandoc` templates (not `dotter` templates)
```zsh
[ERROR] Creating template "pandoc/templates/eisvogel.latex" -> "/home/salkin/.pandoc/templates/eisvogel.latex" but target file already exists. Skipping...
```

**Comment by SuperCuber** [comment]
For the first issue, check out "complex targets" on the configuration wiki page (I'm on mobile so cannot link). Those allow you to override the type of a file. In the next release I expect to add the ability to apply a type to a directory, sounds something that should be useful in your case.

For the second error, if you're sure the file that already exists is unneeded you can use `--force` to overwrite it.

**Comment by SuperCuber** [comment]
@salkin-mada Did that answer your question?

**Comment by salkin-mada** [comment]
@SuperCuber  Yes.
Perfekt will check out the complex targets. Also, as you mention, being able to do this with directories sounds like a very good thing to have. Thanks.

**Comment by sneko** [comment]
https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#complex-target

:)
