### ISSUE TITLE
[FEATURE] Parameter expansion in file paths

### ISSUE THREAD

**Issue by RasmusBertell** [SuperCuber/dotter#41]
**Is your feature request related to a problem? Please describe.**

I'd like to define file targets with path depending on the XDG variables. I think it would be better to not rely on absolute paths.

**Describe the solution you'd like**

Ideally I'd like to define files with command `"tmux.conf" = "$XDG_CONFIG_HOME/tmux/tmux.conf"` but currently it results in directory in my dotfiles folder called `$XDG_CONFIG_HOME`

**Describe alternatives you've considered**

Alternative would be to not change the current behaviour and define paths without parameter expansion.

**Additional context**

It might cause some problems when deploying to a brand new system if your XDG configurations are inside your dotfiles. I don't have an answer how to solve this, but perhaps it could be done with variables somehow.

**Comment by SuperCuber** [comment]
It's definitely possible to expand variables inside the path (in fact it's just a function away with the `shellexpand` library that I already use)

I don't have a good solution for XDG configuration inside dotfiles either, other than needing to load the changes and deploy again.

**Comment by RasmusBertell** [comment]
Perhaps there could be some sort of pre-deployment hook with which you could define a shell script that was executed before deployment. That way you could export the parameters in the script but it could be a security risk.

One could also just include the script in the dotfiles and add a section in readme about running the script or exporting the parameters manually, so I don't really think it is a problem if left out.

**Comment by SuperCuber** [comment]
>it could be a security risk

I don't think security is a concern in this, you shouldn't be deploying other people's setups anyways because they could be overwriting all your own files (like shell init file) which is a security concern anyways.

I don't think there's enough of a use case for a pre-deployment hook yet, but it is something I have considered before (for example, there was a use case of wanting to `touch` or `mkdir` something to make sure it exists)

**Comment by RasmusBertell** [comment]
> I don't think security is a concern in this, you shouldn't be deploying other people's setups anyways because they could be overwriting all your own files (like shell init file) which is a security concern anyways.

I totally overlooked that, thanks for pointing it out.

> I don't think there's enough of a use case for a pre-deployment hook yet, but it is something I have considered before (for example, there was a use case of wanting to touch or mkdir something to make sure it exists)

One use case I could think of would be with a post-deployment hook, I could for example update all vim plugins through a script automatically. These hooks are however starting to sound like a feature request of their own.

**Comment by SuperCuber** [comment]
@RasmusBertell I opened #42 so that this is at least recorded for now, if you have anything to add there you're welcome to.

**Comment by SuperCuber** [comment]
Closed in https://github.com/SuperCuber/dotter/commit/b029893fb83dd08927bf98954a60b1b1fe811711

**Comment by RasmusBertell** [comment]
Just tested this and it works like a charm. Thank you so much for the fast work.
