### ISSUE TITLE
[BUG] No elevation of privileges when overwriting existing files belonging to root

### ISSUE THREAD

**Issue by LokiVKlokeNaAndoke** [SuperCuber/dotter#47]
## Environment
- **OS**: Arch linux
- **Dotter version**: Dotter 0.11.0

## Description
No elevation of privileges when overwriting existing files belonging to root.

## Reproduction
Add this to the config and an appropriate `makepkg.conf` in the dotfiles directory:
```toml
[makepkg.files]
"makepkg.conf" = { target = "/etc/makepkg.conf", type = "symbolic", owner = "root" }
```

Run `dotter -f`

### Expected behavior
Dotter requests the password and `/etc/makepkg.conf` is replaced with a symlink.

### Actual behavior
Dotter fails with an error message:
```
[ WARN] Creating symlink "etc/makepkg.conf" -> "/etc/makepkg.conf" but target isn't a symlink. Forcing.
[ERROR] Failed to create symlink "etc/makepkg.conf" -> "/etc/makepkg.conf"
Caused by:
    remove symlink target while forcing
    Permission denied (os error 13)
```
Also, the password wasn't requested.

**Comment by LokiVKlokeNaAndoke** [comment]
This probably has something to do with [this line](https://github.com/SuperCuber/dotter/blob/ddca095754ed596fd25268ba4a97ac41fc0b5212/src/deploy.rs#L427).

**Comment by SuperCuber** [comment]
You're right, it should use the custom `filesystem::remove_file` method. (missed it in other places too)
