### ISSUE TITLE
Why does the `force` flag overrides the `dry run`?

### ISSUE THREAD

**Issue by vessd** [SuperCuber/dotter#49]
### Environment
If applicable, provide the following details:
- **OS**: Arch Linux
- **Dotter version**: 0.11.0

### The question
Why does the `force` flag overrides the `dry run`? The `force` flag allows me to overwrite existing files and I expect that the `dry run` mode will display a list of files that will be overwritten.

**Comment by SuperCuber** [comment]
Dry-run + force doesn't really make sense to me - but it does make sense that dry run should detect files that would be skipped and notify you (it currently doesn't - for ease of implementation, although I will take a look at whether it's easily changeable)

The way you see it, what should be the difference between -d and -df?

**Comment by vessd** [comment]
I would prefer the `dry run` mode to show me the actions that will be performed.
`-d` will show me an error that the file exists and will not be overwritten and `-df` will tell me that the file exists and will be overwritten.

**Comment by vessd** [comment]
My point is that the `dry run` flag should have the highest priority, even if it doesn't make much sense.

**Comment by SuperCuber** [comment]
> `-d` will show me an error that the file exists and will not be overwritten and `-df` will tell me that the file exists and will be overwritten.

I think this is a pretty good idea, and will definitely do this if I implement `-d` detecting these situations.

And it does make sense to me for `-d` to take priority in that case, although it would make as much sense to just have it error out when they're used together.

**Comment by SuperCuber** [comment]
I'm saving this for after #36 since that will be restructuring quite a bit of code that uses this flag.

**Comment by SuperCuber** [comment]
This is how it works now in master
