### ISSUE TITLE
[BUG] Unable to handle binary files

### ISSUE THREAD

**Issue by JP-Ellis** [SuperCuber/dotter#54]
## Environment
- **OS**: Linux 
- **Dotter version**: `0.12.1`

## Description
Dotter appears to be unable to handle non-text files.  In my case, I have committed a png file used as a background which is causing issues.  The error message is:

```
[ERROR] Failed to create symlink "sway/background.png" -> "/home/josh/.config/sway/background.png"
Caused by:
    detect symlink's current state
    get source state
    read contents of file that isn't symbolic or directory
    stream did not contain valid UTF-8
```

I have tried manually specifying that this file ought to be symlinked (in order to avoid issues from attempting to parse the file)
```
"sway/background.png" = { target = "~/.config/sway/background.png", type = "symbolic" }
```
but I still get the error.

### Expected behavior
If a symbolic link is requested, I don't think dotter has any need to try and even read the file, and if unspecified, non-text files should not cause the program to crash.

**Comment by SuperCuber** [comment]
This is a result of the big refactor a couple of tags ago.

(Notes to self)

Relevant lines: https://github.com/SuperCuber/dotter/blob/17d9e5653037e3b95d541aea0df18d701499c321/src/filesystem.rs#L727 , 
https://github.com/SuperCuber/dotter/blob/17d9e5653037e3b95d541aea0df18d701499c321/src/filesystem.rs#L554

Todo:
- [ ] Have file contain Option<String>
- [ ] Correctly handle this error case
- [ ] Correctly handle the option everywhere it's used
- [ ] Add a unit test for this
