### ISSUE TITLE
[BUG] Dotter deploy unable to run after the first time on macos due to no /proc/self

### ISSUE THREAD

**Issue by shunsambongi** [SuperCuber/dotter#62]
## Environment
- **OS**: macOS Big Sur
- **Dotter version**: Dotter 0.12.3

## Description
Dotter deploy works the first time I run it, but errors on subsequent attempts to run the command.

## Reproduction
A minimal reproducible example: 
1. Create `.dotter/global.toml`:
  ```toml
  [bash.files]
  bashrc = "~/.bashrc"
  ```
2. And `.dotter/local.toml`:
  ```toml
  packages = ["bash"]
  ```
3. Run `touch bashrc` to create the `bashrc` file.
3. Run `dotter` to deploy `bashrc`.
4. Immediately run `dotter` again.

### Expected behavior
The first time `dotter` is run, it should successfully deploy the file (which it does). The second time `dotter` is run, it should successfully deploy again (although there will be no change to the target).

### Actual behavior
The second time I run `dotter`, I get this error:
```
[ERROR] Failed to update symlink "bashrc" -> "/Users/my_username/.bashrc"
Caused by:
    set target symlink owner
    detect if file is owned by the current user
    get metadata of /proc/self
    No such file or directory (os error 2)
```
Running with `RUST_LOG=trace dotter` doesn't give me any other output.

I'm not an expert on any of this, but I guess this is happening because macos doesn't have `/proc/self` like linux does. The error comes from this [line](https://github.com/SuperCuber/dotter/blob/a6ee8f17330796b55db14a1a372c953f469c6054/src/filesystem.rs#L269-L272). 

I'm a beginner in rust, but I would also be happy to try to contribute a bugfix.

**Comment by SuperCuber** [comment]
You're right - as you can see the current way that this condition is detected is by comparing the uids of the file and the `/proc/self` file (which is owned by the current user)

Not sure why I did it that way, it probably was the easiest at the time. I don't have a macos computer to test this on so I would appreciate a contribution for this :)
