### ISSUE TITLE
[FEATURE] Undeploy git submodules

### ISSUE THREAD

**Issue by lasse16** [SuperCuber/dotter#67]
**Is your feature request related to a problem? Please describe.**
Upon undeploying git submodules, which are included in my dotfile repository, I am prompted to delete the empty folders leftover in the `.git` of the submodule. These usually accounts for about one hundred prompts each undeploy.

If I cancel the undeploy, and start it again with the `-y` flag, some folders inside the submodules are leftover and require manual deleting.

**Describe the solution you'd like**
My suggestion for fixing is a special prompt, when a submodule ( `.git` directory) is detected. 
Confirming in this special prompt should unlink the entire submodule.

**Describe alternatives you've considered**
Simple, alternative solution is to  run `dotter undeploy -y` and  confirm all prompts. This does work, but hides all other prompts, which might be important.

**Additional context**
My submodules are mainly vim plugins. They are "hidden" three or four folders deep inside my dotfiles.

**Comment by SuperCuber** [comment]
Another idea that I thought of would be to provide a way to mark a whole directory to be on symlink instead of being recursively traversed, in which case undeploying it would just remove that one symlink...

I'll check which solution is easier to implement but I think both are good to have

**Comment by SuperCuber** [comment]
I looked at this again and I think a good idea would be to have 
```toml
a = "b"
"a/.git" = ""
```
Using the already existing feature where `""` disables that directory.

Looks like this does not currently work though...

Would this fix work for you?

**Comment by lasse16** [comment]
That solution is not working for me. 
The `.git` directory is needed. It keeps track of the version of my plugins, and my plugin manager uses that directory to check whether they are up to date or not. 

I am using `dotter undeploy -y` for now, and did not run into any other problems yet.
So this is a low-priority issue.

**Comment by lasse16** [comment]
A possible solution that just come to mind:

Explicitly specifying the type of link results in "a/.git" being symlinked, with no recursion ?
As in your example above, but with a complex target, so that the symlink is non-recursive.

```toml
a = "b"
# Update the directory link so .git is not further recursed
"a/.git" = {target="b", type="symbolic"}
```

**Comment by SuperCuber** [comment]
> The .git directory is needed

I don't think I understand the use case then. Is the plugin manager operating on the repo at the target location? I'm not sure why you're deploying it through dotter instead of just cloning it there. (unless you're using the templating?)

> Explicitly specifying the type of link results in "a/.git" being symlinked, with no recursion ?

Currently all configuration recurses as is (even `append` and `prepend` IIRC) and I think this should stay like that (especially since changing it is breaking), but maybe adding a `recursive = false` flag will be useful.

So in your case you would do
```toml
a = "b"
"a/.git" = {target="b/.git", type="symbolic", recursive=false}
```

And regardless this will need the fix of allowing more specific path to override a less specific path.

**Comment by lasse16** [comment]
You are right. I overlooked the option of changing the runtimepath for my vim, then I do not need to symlink it.
