### ISSUE TITLE
Update to handlebars v4.0.0 (blocked)

### ISSUE THREAD

**Issue by lasse16** [SuperCuber/dotter#68]
## Environment
- **OS**: WSL Ubuntu 20.04
- **Dotter version**: 0.12.4

## Description
Using the `{{#each list}` syntax in Handlebar file inserts a new line after each iteration.
Evaluating the same syntax on the Handlebar website does not insert a new line. 

## Reproduction
In  my template file I included:
``` bash
  {{#each ssh.key-files}}
    ssh-add {{this}};
    {{/#each}}
```
`local.toml` contains:
``` bash 
ssh.key-files = [ "~/.ssh/fileA", "~/.ssh/fileB", "~/.ssh/fileC", "~/.ssh/fileD" ]
```
`dotter deploy` now renders the template.

### Expected behavior
Resulting file section:
``` bash
ssh-add ~/.ssh/fileA;
ssh-add ~/.ssh/fileB;
ssh-add ~/.ssh/fileC;
ssh-add ~/.ssh/fileD;

```

### Actual behavior
``` bash

ssh-add ~/.ssh/fileA;

ssh-add ~/.ssh/fileB;

ssh-add ~/.ssh/fileC;

ssh-add ~/.ssh/fileD;

```

There is a new line inserted between each iteration of the loop.
I created a quick [reproduction](https://handlebarsjs.com/playground.html#format=1&currentExample=%7B%22template%22%3A%22%20%20%7B%7B%23each%20ssh.keyfiles%7D%7D%5Cn%20%20%20%20ssh-add%20%7B%7Bthis%7D%7D%5Cn%20%20%7B%7B%2Feach%7D%7D%22%2C%22partials%22%3A%5B%5D%2C%22input%22%3A%22%7B%5Cn%20%20ssh%3A%7B%5Cn%20%20keyfiles%3A%20%5B%5Cn%20%20%20%20%5C%22fileA%5C%22%2C%5Cn%20%20%20%20%5C%22fileB%5C%22%2C%5Cn%20%20%20%20%5C%22fileC%5C%22%2C%5Cn%20%20%20%20%5C%22fileD%5C%22%2C%5Cn%20%20%5D%2C%5Cn%7D%5Cn%7D%5Cn%22%2C%22output%22%3A%22%20%20%20%20ssh-add%20fileA%5Cn%20%20%20%20ssh-add%20fileB%5Cn%20%20%20%20ssh-add%20fileC%5Cn%20%20%20%20ssh-add%20fileD%5Cn%22%2C%22preparationScript%22%3A%22%2F%2F%20Handlebars.registerHelper('loud'%2C%20function(string)%20%7B%5Cn%2F%2F%20%20%20%20return%20string.toUpperCase()%5Cn%2F%2F%20%7D)%3B%5Cn%22%2C%22handlebarsVersion%22%3A%224.7.7%22%7D) on the handlebars website with the input data  translated to json. There is no new line inserted.

**Comment by SuperCuber** [comment]
IIRC this is already an open issue in the handlebars-rs repository, but if not you should open it there, as I just depend on it :)

I might be using an outdated version where it's fixed though - I'll update and check if that fixes it.

**Comment by lasse16** [comment]
I found a [PR](https://github.com/sunng87/handlebars-rust/pull/404), which is somewhat related on their Github.

The PR is closing this [issue](https://github.com/sunng87/handlebars-rust/issues/258), which is also related to whitespace.

Those two are the only somewhat related mentions on their Github I could find.
My Rust is too bad to understand the changes made in the PR, could you take a look at it @SuperCuber ?

The PR was merged on the fourth of January this year, so it might  already be fixed in the most recent version.
If not, I'm going to open an issue on their Github and ask whether it is intended or a bug.

Ohh and thanks for the quick answer and cooperation :).

**Comment by lasse16** [comment]
I also figured out a workaround for now. ( Might also be the intended way to solve this problem )

Handlebar offers the ability to control whitespace with the `~` character. [Section on the Handlebar website](https://handlebarsjs.com/guide/expressions.html#whitespace-control)

Inserting this character in the  following way, gets rid of the whitespace between each iteration and at the beginning of the loop.
<pre>
  {{<b>~</b>#each ssh.key-files}}
    ssh-add {{this}};
    {{<b>~</b>/#each}}
</pre>
The snippet results in the expected result from the opening statement.

**Comment by SuperCuber** [comment]
Yep, this is also what I currently do. (for example with if blocks)

**Comment by SuperCuber** [comment]
Oh just saw the seocnd comment, the second issue is the one I was recalling. I'll check it out.

**Comment by SuperCuber** [comment]
Seems like this is indeed merged to the latest handlebars version 4.0 which got released a couple days ago. However another crate I use called handlebars_misc_helpers did not update to it yet, causing a version mismatch.

I've opened [an issue](https://github.com/davidB/handlebars_misc_helpers/issues/31) there but for now it's blocking me from upgrading, but when it's fixed it should Just Work™️

**Comment by lasse16** [comment]
Ok, thanks for the work :)

**Comment by SuperCuber** [comment]
I'll reopen this as a reminder to update when the library updates

**Comment by RasmusBertell** [comment]
Just a heads up that while your opened issue remains unresolved in handlebars_misc_helpers repo they seems to have updated the handlebars dependency to 4.0 in 0.12.x releases.

**Comment by SuperCuber** [comment]
@RasmusBertell thanks, updated.
