### ISSUE TITLE
How is `~` expanded?

### ISSUE THREAD

**Issue by lasse16** [SuperCuber/dotter#72]
### Environment
If applicable, provide the following details:
- **OS**: WSL Ubuntu 20.04
- **Dotter version**: 0.12.4
- **Additional relevant information**
Bash as shell

### The question
How is `~` in templates in Bash expanded?

In order to set some environment variables when deploying dotter, I set up my `pre_deploy.sh` hook and source the rendered template from a wrapper script I run, instead of `dotter deploy`.

```
# local.toml
"environment.dotfile_folder"="~/dotfiles"
```

```
# pre_deploy.sh
echo " test " >> "{{environment.dotfile_folder}}/folder_shortcuts.txt"
```

```
# rendered pre_deploy.sh
echo " test " >> "~/dotfiles/folder_shortcuts.txt"
```

The problem here, is that in Bash tilde in a string is not expanded. Shellcheck suggest the solution to use `$HOME` instead of `~`.
And fair enough , replacing `"~/dotfiles"` with `"$HOME/dotfiles"` in `local.toml` solves the issue.

However I was under the assumption that Dotter already did this when rendering the template. The same way `~` is replaced on Windows. 
This might be a faulty assumption of mine, but it still might be a useful feature.

Was this a faulty assumption or is it a bug in my setup? I agree that my setup is rather exotic and fragile, and that there is probably a better solution. Especially when #61 / #60 are merged/implemented.

**Comment by SuperCuber** [comment]
Tilde is expanded on the dotter side only in file section, and IIRC specifically in the target. Seems like your local.toml snippet is from the variables part which are not processed at all

**Comment by lasse16** [comment]
Ahh, that does make sense. Thanks for the answer.
Then my solution, by replacing the tilde is the intended way of doing this.

I suggest putting that non-processing of variables somewhere explicit in the documentation.
I read the docs quite a few times in the last days and that wasn't clear to me. 

Thank you anyway :D
