### ISSUE TITLE
[FEATURE] Support shebang in hooks

### ISSUE THREAD

**Issue by mythmon** [SuperCuber/dotter#73]
## Environment
- **OS**: Ubuntu (In ChromeOS)
- **Dotter version**: 0.12.4
- **Additional relevant information**

## Description
Hooks, like `post_deploy.sh`, are always executed in `sh`, ignoring any shebang line in the script.

## Reproduction
* Have a system where `sh` is not a symlink to `bash`.
* Create a `post_deploy.sh` file (or another hook) containing
  ```sh
  #!/usr/bin/env bash
  readlink /proc/$$/exe
  ```
* Run `dotter deploy` (or run the hook another way through Dotter).

### Expected behavior
The `readlink` command should show the shell listed in the shebang line (bash).

### Actual behavior
The `readlink` command shows `sh`, or in my case `dash`.

This is a problem because `sh` and `dash` don't have the same features as `bash` (or another script runner I might use). This makes my dotfiles less portable, as some systems use bash for the system shell (Arch), and some don't (Ubuntu).

**Comment by mythmon** [comment]
I believe a solution to this is to run the command as `sh -c $hook_file` instead of `sh $hook_file`, but that requires that `$hook_file` be executable. I wasn't quite sure how to do that in Rust.

**Comment by SuperCuber** [comment]
You're right that currently the script will always be ran by sh - but I don't think this is an issue from a portability standpoint, since sh should have strictly less features than bash and both are POSIX-compliant, which means as long as your script only uses POSIX features it should be completely portable. Am I missing something?

**Comment by mythmon** [comment]
Yes, I could write my script using only POSIX features, and it would probably run everywhere. However, right now I have a script that runs fine on one system, and breaks in confusing ways on another. The first system has `sh` symlinked to bash, and the second has it symlinked to dash.

The script in question is

```sh
#!/bin/bash
SYSTEMD_ROOT="${HOME}/.config/systemd/user"

function enable_service() {
  if [[ -f "${SYSTEMD_ROOT}/$1" ]] && ! [[ -f "${SYSTEMD_ROOT}/multi-user.target.wants/$1" ]]; then
    echo "Enabling and starting systemd unit $1"
    systemctl --user --now enable $1
  fi
}

{{ #if dotter.packages.taskwarrior }}
enable_service task-sync.timer
{{ /if }}
```

However, a `post_deploy.sh` as simple as this also fails:

```sh
#!/usr/bin/env bash
function foo() {
  echo hello from foo
}
foo
````

The error it gives is:

```
> dotter deploy -v
.dotter/cache/.dotter/post_deploy.sh: 2: .dotter/cache/.dotter/post_deploy.sh: Syntax error: "(" unexpected
[ERROR] Failed to deploy
Caused by:
    run post-deploy hook
    subshell returned error
```

It is certainly very surprising that the shebang line is ignored.

**Comment by SuperCuber** [comment]
Hm... Running it as an executable would require a shebang, which would be a breaking change.
This is the code in question

https://github.com/SuperCuber/dotter/blob/ab5381193ff49abd1ed1178c2de69130e2668352/src/hooks.rs#L40

Instead the code would need to
1) Mark the file as executable
2) `Command::new(file)` to just run it like `./file`

Should be easy to implement - I'm just not completely convinced yet that the breaking change is worth it.

(I was also going to suggest you use a heredoc into `bash` manually to simulate a shebang but seems like `dash` doesn't support that, and it's not a great solution anyways)

**Comment by mythmon** [comment]
I'm not sure that the shebang *is* required, if the file is compatible with whatever `sh` is symlinked to. I think it only needs to be executable (which would be handled in your plan above):

```shell
> ls -lah
> echo "echo hello" > my_script.sh
> ls -lah
-rw-r--r-- 1 mythmon mythmon 11 Jun  8 22:40 my_script.sh
> dash -c my_script.sh
dash: 1: my_script.sh: not found
> dash -c ./my_script.sh
dash: 1: ./my_script.sh: Permission denied
> chmod +x my_script.sh
> dash -c ./my_script.sh
hello
```

**Comment by SuperCuber** [comment]
Actually, I tried this script:
```sh
ps -p $$
```
Which is supposed to print the current shell. Running `./test` from zsh, it printed sh - seems like it uses some default when there's no shebang. Maybe this is not breaking after all...

**Comment by kakawait** [comment]
>     1. Mark the file as executable

I'll never chocked that any executable script, even if it's triggered by other script using hooks must have executable right to be run.

>     2. Command::new(file) to just run it like ./file

My 2 cents advice, but I think is still better to do not limit the executable to sh only (which can be very limited) and let shebang determine the running env.

**Comment by jmerdich** [comment]
This also seems a major pain point for me, starting out and intending to also use this on an enterprise-y machine where sh is tcsh (*internal vomitting*). If you've never used tcsh before, its concept of "error handling" usually doesn't involve printing where the error happened, which makes it nearly unusable even if sticking to POSIX syntax.

I think that if a file is executable, you should execute it, full-stop. Assuming it's a shell script really violates the principle of least surprise. This also allows non-sh things as hooks, such as python, perl, or rust-script :stuck_out_tongue: .

If you care about back-compat, my opinion is the following:
 - If executable, execute it.
 - If not, print a warning and try to run it with sh.

I could try my hand at a PR if you're agreeable?

**Comment by SuperCuber** [comment]
@jmerdich this seems like the best solution to me. PR is indeed appreciated, the point of interest is here https://github.com/SuperCuber/dotter/blob/e23dce59e91b5db641cc3c9db2847efc9a68eff4/src/hooks.rs#L7

**Comment by kakawait** [comment]
> @jmerdich this seems like the best solution to me. PR is indeed appreciated, the point of interest is here
> 
> https://github.com/SuperCuber/dotter/blob/e23dce59e91b5db641cc3c9db2847efc9a68eff4/src/hooks.rs#L7

I've checked a little, but I'm totally new on code base and Rust.
I've small question, why do you copy permission from `source` to `&target.target`.

https://github.com/SuperCuber/dotter/blob/master/src/actions.rs#L571

In case of `post_deploy.sh` it will result on

```
Copying permissions ".dotter/post_deploy.sh" -> "/tmp/dotter_temp" as current user
``` 

But script file is ran from `.dotter/cache/.dotter/post_deploy.sh`

The problem is that permission is not copied and even if `.dotter/post_deploy.sh` is `-rwxr-xr-x`, `.dotter/cache/.dotter/post_deploy.sh` will not be executable.

Changing 

```rust
fs.copy_permissions(source, &target.target, &target.owner)
        .context("copy permissions from source to target")?;
```

to 

```rust
fs.copy_permissions(source, &cache, &target.owner)
        .context("copy permissions from source to target")?;
```

seems to work but I'm a bit afraid about side effects...

**Comment by SuperCuber** [comment]
> > @jmerdich this seems like the best solution to me. PR is indeed appreciated, the point of interest is here
> > 
> > https://github.com/SuperCuber/dotter/blob/e23dce59e91b5db641cc3c9db2847efc9a68eff4/src/hooks.rs#L7
> 
> I've checked a little, but I'm totally new on code base and Rust.
> I've small question, why do you copy permission from `source` to `&target.target`.
> 
> https://github.com/SuperCuber/dotter/blob/master/src/actions.rs#L571
> 
> In case of `post_deploy.sh` it will result on
> 
> ```
> Copying permissions ".dotter/post_deploy.sh" -> "/tmp/dotter_temp" as current user
> ``` 
> 
> But script file is ran from `.dotter/cache/.dotter/post_deploy.sh`
> 
> The problem is that permission is not copied and even if `.dotter/post_deploy.sh` is `-rwxr-xr-x`, `.dotter/cache/.dotter/post_deploy.sh` will not be executable.
> 
> Changing 
> 
> ```rust
> fs.copy_permissions(source, &target.target, &target.owner)
>         .context("copy permissions from source to target")?;
> ```
> 
> to 
> 
> ```rust
> fs.copy_permissions(source, &cache, &target.owner)
>         .context("copy permissions from source to target")?;
> ```
> 
> seems to work but I'm a bit afraid about side effects...


Nice catch, but the correct fix here would be in the calling code - the file that needs to be executed is not the cached file but the target.

**Comment by kakawait** [comment]
Ok I'll check, I've already did the piece of code to check if file is executable (and if not a dir :)). I'll now check why calling code is calling from `.cache` rather than target.
