### ISSUE TITLE
Specify target directories instead of files?

### ISSUE THREAD

**Issue by kflak** [SuperCuber/dotter#78]
### Environment
If applicable, provide the following details:
- **OS**: Arch Linux
- **Dotter version**: 0.12.4

### The question
I am considering ditching dotbot for dotter, but before I make the leap I would just like to make sure of one thing: in the dotbot config I can specify directories that get linked over as-is, for example: 
```
- link:
    $HOME/.config/SuperCollider         : SuperCollider/
    $HOME/.config/alacritty             : alacritty/
    $HOME/.config/bspwm                 : bspwm/
    $HOME/.config/dunst                 : dunst/
```
etc...

I would love to be able to pull off a similar trick with dotter, but can't find any docs describing the difference between file and directory in the configs...

**Comment by SuperCuber** [comment]
Hey, when linking a directory somewhere it is executed recursively for all files and directories inside it. There's an issue open for being able to disable recursing and link the whole directory but it's not implemented yet.

**Comment by kflak** [comment]
Great, thanks!
