### ISSUE TITLE
How to deal with "target isn't a symlink" errors

### ISSUE THREAD

**Issue by johnhamelink** [SuperCuber/dotter#80]
### Environment
If applicable, provide the following details:
- **OS**: Arch Linux
- **Dotter version**: 0.12.5

### The question
Yesterday I moved all my dotfile maintenance responsibilities to dotter, and so far it works really well overall! One file I'm trying to manage is `~/pavucontrol.ini` - the configuration file for the pulse audio tool  of the same name. It seems that pavucontrol likes to overwrite the symlink created by dotter with a new file, so when I try to resync dotter, it complains that the file is no longer a symlink. I learned from [this issue](https://github.com/SuperCuber/dotter/issues/77) that using the `template` option would allow for the file to be copied. The error output makes it clear I can use `--force` to rectify this error, but that would apply to all the files dotter works with, not just the one file with the issue. Perhaps having being able to do `{ target = "/example.txt", type = "template (hopefully copy soon)", force = "true" }` would work better for many dealing with a scenario such as mine?

```
[ INFO] [-] symlink "pavucontrol/config.ini" -> "/home/john/.config/pavucontrol.ini"
[ERROR] Deleting "pavucontrol/config.ini" -> "/home/john/.config/pavucontrol.ini" but target isn't a symlink. Skipping.
[ INFO] [+] template "pavucontrol/config.ini" -> "/home/john/.config/pavucontrol.ini"
[ERROR] Creating template "pavucontrol/config.ini" -> "/home/john/.config/pavucontrol.ini" but target file already exists. Skipping.
[ERROR] Some files were skipped. To ignore errors and overwrite unexpected target files, use the --force flag.
```

**Comment by SuperCuber** [comment]
Using force in this case should be a one-time thing. The way dotter goes from a file being a symlink to template as you can tell is by first deleting the symlink then creating the template, but it's refusing to do the first step because it expects it to be a symlink of course.

Using --force will make it delete anyways then create a template, and then it will never complain again - since pavucontrol will not actually change the file anymore.

**Comment by johnhamelink** [comment]
Yep, you were right! I thought that pavucontrol was deleting then recreating the file, but after some fairly heavy use of both dotter & pavucontrol, this doesn't seem to be the case.

Thanks!
