### ISSUE TITLE
[BUG] dotter init fails when any files are present in CWD

### ISSUE THREAD

**Issue by Diomendius** [SuperCuber/dotter#81]
## Environment
- **OS**: Arch Linux up-to-date as of 2021-08-09
- **Dotter version**: Dotter 0.12.5

## Description
When `dotter init` is run in a directory containing any file besides a `.dotter` directory, the command fails with the following output:
```console
[ERROR] Failed to initalize directory
Caused by:
    save dummy config
    save global config
    serialize data
    unsupported Rust type
```

## Reproduction
In a suitable temporary directory, run:
```sh
touch file
dotter init
```

## Additional notes
I have tracked down the source of this bug and have submitted a pull request (#82).

I'm not sure how this was missed until now; maybe it was a regression and `dotter init` hasn't been tested since it was first implemented.

**Comment by SuperCuber** [comment]
@Diomendius A release including the PR has been created :D
