### ISSUE TITLE
[FEATURE] Ideas for making it easier to work with systemd files

### ISSUE THREAD

**Issue by johnhamelink** [SuperCuber/dotter#85]
**Is your feature request related to a problem? Please describe.**
I often want to run scripts periodically, and I tend to do this using `systemctl --user`.

**Describe alternatives you've considered**

A post-hook script partially does the job, but I had to find out the I could expand the current directory to an absolute path with `~+` in the bash script. Worse still, when building out a systemd timer I need to provide an absolute path to the accompanying service file: unfortunately the only way to do this in dotter is to use a template with a hack to get the home directory, and templates only work when you have a destination for the template to be rendered to, which means I need to setup a destination for the file, and then I need to run systemctl against that destination directory separately. Phew.

So the process is now:

1. Create a `.dotter/post_deploy.sh` script with the following:

```bash
#!/usr/bin/env bash

echo "Enabling all timers and services"
find ~+ -name '*.service'  -print | xargs -i systemctl --user enable {}
find ~/.cache/dotter-templates/ -name '*.timer'  -print | xargs -i systemctl --user enable {}
```

2. In your `.dotter/global.toml`, add something like:

```toml
[isync.files]
"isync/config" = "~/.mbsyncrc"
# This destination isn't required by systemd, we're just putting our 
# generated template somewhere vaguely sensible.
"isync/systemd/mbsync.timer" = "~/.cache/dotter-templates/mbsync.timer"
```

3. Your `isync/systemd/mbsync.timer` should look something like:

```systemd
[Unit]
Description=Mailbox Sync timer

[Timer]
OnBootSec=2m
OnUnitActiveSec=5m
Unit={{command_output "echo -n ~" }}/.dotfiles/isync/systemd/mbsync.service

[Install]
WantedBy=timers.target
```

As you can see, this is quite a lot of work.

**Describe the solution you'd like**

1. Having the ability to run a command on the destination file once it's been updated would be very handy and would negate the need for a post-deploy hook in this case.
2. Provide a template type where the destination doesn't matter: the destination is simply a place for the file to be rendered. The path would be available from templates and in the command defined by feature 1.
3. Perhaps a convenience function to replace the `command_output` hack in the timer script itself?
4. It would also be nice to be able to get the dotfiles directory as a variable in the post-hook script.

**Additional context**

**Comment by SuperCuber** [comment]
Why not just use something like
### global.toml
```toml
my_service_files_dir = "~/.config/systemd/user"
```
### pre_deploy
```sh
{{{#if dotter.packages.package_that_inclues_service}}
systemctl --user disable my_service1.service my_service2.timer ...
{{/if}}
```

post deploy - same but enable

### my_service.timer
```systemd
[Unit]
Description=Mailbox Sync timer

[Timer]
OnBootSec=2m
OnUnitActiveSec=5m
Unit=mbsync.service

[Install]
WantedBy=timers.target
```

According to [this page](https://wiki.archlinux.org/title/systemd/User) i think your problem is just you're putting the files in the wrong place.

Also you should read about the [builtin dotter variables](https://github.com/SuperCuber/dotter/wiki/Setup-and-Configuration#builtin-variables) - I haven't read too deeply into the post but maybe `dotter.files` could help you.

Do tell me if this doesn't help you and I should re-read your post though :P

**Comment by SuperCuber** [comment]
Feel free to reopen this if it isn't resolved.
