### ISSUE TITLE
Failed to deploy

### ISSUE THREAD

**Issue by leontepe** [SuperCuber/dotter#93]
### Environment
- **OS**: macOS
- **Dotter version**: 0.12.9
- Dotfiles in `~/.dotfiles`
- Error message:
```
[ERROR] Failed to deploy
Caused by:
    get a configuration
    merge configuration files
    get info of package default
```

### The question
I installed dotter using cargo. I would like to keep dotter binaries out of the repo, since I want to save the space and think only source files should go into repos. I can't seem to deploy like this, though. I already tried running `dotter -g ~/.dotfiles/.dotter/global.toml` but that didn't work either.

What's the problem here? How can I fix this?

**Comment by SuperCuber** [comment]
Are you running from `~/.dotfiles` as your working directory? (You are supposed to)

If you are, is there more to the error?

**Comment by leontepe** [comment]
> Are you running from `~/.dotfiles` as your working directory? (You are supposed to)

Yup.

> If you are, is there more to the error?

Just what I've already provided:
```
[ERROR] Failed to deploy
Caused by:
    get a configuration
    merge configuration files
    get info of package default
```

**Comment by SuperCuber** [comment]
Post global.toml and local.toml (and included if you have)

**Comment by leontepe** [comment]
`global.toml`:
```
[zsh.files]
# this file sets $ZDOTDIR
"zsh/env_init" = "$HOME/.zshenv"
"zsh/env" = "$XDG_CONFIG_HOME/zsh/.zshenv"
"zsh/rc" = "$XDG_CONFIG_HOME/zsh/.zshrc"
"zsh/profile" = "$XDG_CONFIG_HOME/.zprofile"

[nvim.files]
nvim = "$XDG_CONFIG_HOME/nvim"
```

`local.toml`:
```
includes = []
packages = ["default"]

[files]

[variables]
```

Now that I see this, did I maybe delete some of the necessary boilerplate in `global.toml`?

**Comment by SuperCuber** [comment]
You're selecting the wrong thing in `packages` of local.toml. In your case it should be `["zsh", "nvim"]`

I should change the error message to be more informative so keep the issue open :)

**Comment by leontepe** [comment]
It now works, thanks :) can I somehow define a default package list here, though? So that I basically have an empty `local.toml` and just derive everything from the `global.toml`.

**Comment by SuperCuber** [comment]
there's currently no "select all packages" option

**Comment by leontepe** [comment]
would be nice if no `local.toml` exists would mean "select all packages". Seems intuitive to me

**Comment by SuperCuber** [comment]
You could add a special "all" package and have
```toml
[all]
depends =["my","packages"]
```

Then select it in local.toml
