### ISSUE TITLE
[BUG] `watch` does not work when run not as root

### ISSUE THREAD

**Issue by wilbowma** [SuperCuber/dotter#98]
## Environment
- **OS**: Linux distribution / Windows version
> Linux 5.17.6-1-MANJARO
- **Dotter version**: Find out using `dotter -V
> Dotter 0.12.10

- **Additional relevant information**

## Description
The `watch` subcommand fails when not run as root.

## Reproduction
```
> touch /tmp/global.toml
> dotter -g /tmp/global.toml -d watch
[ERROR] Failed to watch repository
Caused by:
    run watch deploy
    I/O error: Permission denied (os error 13)

> sudo dotter -g /tmp/global.toml -d watch
[sudo] password for : 
[ WARN] It is not recommended to run Dotter as root, since the cache files and all files not marked with an `owner` field will default to being owned by root.
If you're truly logged in as root, it is safe to ignore this message.
Otherwise, run `dotter undeploy` as root, remove cache.toml and cache/ folders, then use Dotter as a regular user.
[Dotter] Deploying...

```

### Expected behavior
`watch` should work, and not require root privileges.

### Actual behavior
`watch` does not work at all when run not as root.

**Comment by SuperCuber** [comment]
The error coming from the `watchexec` dependency is not very helpful here sadly. What directory are you running this from? Are all the files in your current directory (and its children) readable? For example if you run `find >/dev/null` do you get any permission denied errors?

It's kind of strange to me that you're getting the `global.toml` from `/tmp`, both of them are intended to be inside your dotfiles repository and you're supposed to have your current directory be the dotfiles repository as well - in that case there shouldn't be any permission denied errors.

As you already ran dotter with root I recommend you follow the warning and run `dotter undeploy` and remove `cache.toml` and `cache/` folders from your `.dotter` folder.

**Comment by wilbowma** [comment]
I'm just used a `global.toml` from `tmp`; I did that for a minimal reproducable example. I also ran the above with `-d` so the cache shouldn't have been updated, I hope.

It looks `find >/dev/null` gives `find: ‘./secure/.fseventsd’: Permission denied`; this is coming from a mounted encrypted image where I've stored my private keys. I suppose the watcher could be having issues with that directory, although it doesn't appear in the config, some others in `./secure` do.

**Comment by SuperCuber** [comment]
The watcher tries to read every file under the current directory regardless of the config - this is probably why.
When you say `some others in ./secure do` do you mean that they are the source file that is symlinked/templated out to the system?

**Comment by wilbowma** [comment]
One of the files in that directory wasn't readable by my user; this file wasn't managed by dotter but still seemed to cause an issue. When I changed the permissions on it, `watch` worked.

`secure/ssh` was managed by dotter. The relevant line from `global.toml` was:
```
"secure/ssh" = { target = "~/.ssh", type="symbolic", recurse=false}
```

The offending file was something to do with the VeraCrypt AFAICT.

**Comment by SuperCuber** [comment]
Seems like this is the source of the problem https://github.com/watchexec/watchexec/issues/149
It's closed supposedly - I'll see if updating the version of the dependency resolves this.

**Comment by SuperCuber** [comment]
Now that I think of it, I will remove the `re-run with -vv` if you're currently running with -vv :P

**Comment by SuperCuber** [comment]
Will be included in the next release

**Comment by wilbowma** [comment]
Great, thanks for the help, and for the tool!
